---
- hosts: all
  remote_user: deploy
  gather_facts: false
  environment:
    CONFIG_PROFILE: "production"
  tasks:
    - name: Copy service file
      become: true
      copy:
        src: "villagebook.service"
        dest: /etc/systemd/system

    - name: Compile frontend app
      local_action: shell shadow-cljs release villagebookUI

    - name: Generate Uberjar on local machine
      local_action: shell lein do clean, uberjar

    - name: Delete old uberjar
      file:
        path: /home/deploy/villagebook-0.1.0-SNAPSHOT-standalone.jar
        state: absent

    - name: Copy uberjar to server
      copy:
        src: ../target/villagebook-0.1.0-SNAPSHOT-standalone.jar
        dest: /home/deploy/
        owner: deploy
        mode: '0644'

    - name: Stop villagebook service
      become: true
      systemd:
        daemon_reload: yes
        state: stopped
        name: villagebook
        enabled: yes

    - name: Run villagebook migrations
      become: true
      become_user: postgres
      shell: cd /home/deploy/ && java -jar villagebook-0.1.0-SNAPSHOT-standalone.jar migrate

    - name: Start villagebook service
      become: true
      systemd:
        daemon_reload: yes
        state: restarted
        name: villagebook
        enabled: yes

    - name: Copy the nginx config file
      become: true
      copy:
        src: nginx.cfg
        dest: /etc/nginx/sites-available/villagebook.cfg

    - name: Create symlink
      become: true
      file:
        src: /etc/nginx/sites-available/villagebook.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart nginx
      become: true
      service:
        name: nginx
        state: restarted
